ecommerce/checkout/urls.py
from django.urls import path 
from . views import checkout, payment, charge, oderView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('payment/', payment, name="payment"),
	path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('', include('checkout.urls', namespace='checkout')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/checkout/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model
# Create your models here.

# Get the user model
User = get_user_model()

class BillingAddress(models.Model):

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address = models.CharField(max_length=100)
	zipcode = models.CharField(max_length=50)
	city = models.CharField(max_length=30)
	landmark = models.CharField(max_length=20)

	def __str__(self):
		return f'{self.user.username} billing address'

	class Meta:
		verbose_name_plural = "Billing Addresses"


# Address Form
class BillingForm(ModelForm):

	class Meta:
		model = BillingAddress
		fields = ['address', 'zipcode', 'city', 'landmark']

ecommerce/checkout/views.py
import stripe
from django.utils.crypto import get_random_string
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Order, Cart
from . models import BillingForm, BillingAddress
from django.views.generic.base import TemplateView


stripe.api_key = settings.STRIPE_SECRET_KEY 

def checkout(request):

	# Checkout view
	form = BillingForm
	
	order_qs = Order.objects.filter(user= request.user, ordered=False)
	order_items = order_qs[0].orderitems.all()
	order_total = order_qs[0].get_totals() 
	context = {"form": form, "order_items": order_items, "order_total": order_total}
	# Getting the saved saved_address
	saved_address = BillingAddress.objects.filter(user = request.user)
	if saved_address.exists():
		savedAddress = saved_address.first()
		context = {"form": form, "order_items": order_items, "order_total": order_total, "savedAddress": savedAddress}
	if request.method == "POST":
		saved_address = BillingAddress.objects.filter(user = request.user)
		if saved_address.exists():

			savedAddress = saved_address.first()
			form = BillingForm(request.POST, instance=savedAddress)
			if form.is_valid():
				billingaddress = form.save(commit=False)
				billingaddress.user = request.user
				billingaddress.save()
		else:
			form = BillingForm(request.POST)
			if form.is_valid():
				billingaddress = form.save(commit=False)
				billingaddress.user = request.user
				billingaddress.save()
				
	return render(request, 'checkout/index.html', context)




def payment(request):
	key = settings.STRIPE_PUBLISHABLE_KEY
	order_qs = Order.objects.filter(user= request.user, ordered=False)
	order_total = order_qs[0].get_totals() 
	totalCents = float(order_total * 100);
	total = round(totalCents, 2)
	if request.method == 'POST':
		charge = stripe.Charge.create(amount=total,
            currency='usd',
            description=order_qs,
            source=request.POST['stripeToken'])
		print(charge)
        
	return render(request, 'checkout/payment.html', {"key": key, "total": total})




def charge(request):
	order = Order.objects.get(user=request.user, ordered=False)
	orderitems = order.orderitems.all()
	order_total = order.get_totals() 
	totalCents = int(float(order_total * 100))
	if request.method == 'POST':
		charge = stripe.Charge.create(amount=totalCents,
            currency='inr',
            description=order,
            source=request.POST['stripeToken'])
		print(charge)
		if charge.status == "succeeded":
			orderId = get_random_string(length=16, allowed_chars=u'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')
			print(charge.id)
			order.ordered = True
			order.paymentId = charge.id
			order.orderId = f'#{request.user}{orderId}'
			order.save()
			cartItems = Cart.objects.filter(user=request.user)
			for item in cartItems:
				item.purchased = True
				item.save()
		return render(request, 'checkout/charge.html', {"items": orderitems, "order": order })



def oderView(request):

	try:
		orders = Order.objects.filter(user=request.user, ordered=True)
		context = {
			"orders": orders
		}
	except:
		messages.warning(request, "You do not have an active order")
		return redirect('/')
	return render(request, 'checkout/order.html', context)

ecommerce/checkout/templates/checkout/charge.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5 text-center">
<h2 class="text-center">Thanks, you for your Orders</h2>
<a href="/my-orders" class="btn btn-success">My Orders</a>
</div>

{% endblock %}

ecommerce/checkout/templates/checkout/index.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
  <h2 class="mb-3">Shipping Address > <span class="text-muted">Checkout</span></h2>
  <div class="row">
    <div class="col-md-9">
     <div class="card mb-5" style="height: auto">
       <div class="card-body">
          <form method="POST">
          {% csrf_token %}

         {{ form | crispy}}
          <button type="submit" class="btn btn-primary float-right">Next</button>
          </form>
       </div>
     </div>
      {% if savedAddress %}
      <h4>Saved Address</h4>
      <div class="card mb-5" style="height: auto">
        <div class="card-body">
          <p><b>Address :</b> {{ savedAddress.address }}</p>
          <p><b>City :</b> {{ savedAddress.city }}</p>
          <p><b>Zipcode :</b> {{ savedAddress.zipcode }}</p>
          <p><b>Landmark :</b> {{ savedAddress.landmark }}</p>
        </div>
        <div class="card-body">
           <a href="{% url 'checkout:payment' %}" class="btn btn-primary float-right">Proceed to Checkout with the saved Address</a>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="col-md-3">
      <div class="card" style="height: auto">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            {% for item in order_items %}
            <li class="list-group-item">{{ item.item.name }} x {{ item.quantity }}</li>
            {% endfor %}
          </ul>
        </div>
           <div class="card-footer">
            <span class="float-left"><b>Order Total</b></span>
            <span class="float-right"><b>$ {{ order_total | floatformat:2 }}</b></span>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

ecommerce/checkout/templates/checkout/order.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
<h2 class="text-center"><strong>Your Ordes</strong></h2>
<div class="row">
	<div class="col-md-12">
		<div class="card mt-5" style="height: auto">
			<div class="table-responsive">
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Order Id</th>
			      <th scope="col">Products</th>
			      <th scope="col">Status</th>
			    </tr>
			  </thead>
			  <tbody>
			    
			    
			    {% for order in orders %}
			    <tr>
			      <th scope="row">{{ forloop.counter }}</th>
			      <td><a href="#">{{ order.orderId }}</a></td>
			      <td>
			      	{% for item in order.orderitems.all %}
			      		{{ item }}
			      		<br>
			      	{% endfor %}
			      </td>
			      <td><span class="badge badge-primary">Processing Your Order</span></td>
			  	</tr>
			      {% endfor %}
			    
			  </tbody>
			</table>
			</div>
		</div>
	</div>
	<div class="col-md-12 my-5 text-center">
		<a href="/" class="btn btn-success">Back to Home</a>
	</div>
</div>
</div>

{% endblock %}

ecommerce/checkout/templates/checkout/payment.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5 text-center">
<h2>Pay with Stripe</h2>
<form action="{% url 'checkout:charge' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ key }}"
    data-description="Complete your order"
    data-amount="{{ total }}"
    data-locale="auto">
</script>
</form>

</div>

{% endblock %}